### ISSUE TITLE
Component that should return random response keeps returning same response

### ISSUE THREAD

**Issue by kennethwolters** [fermyon/spin-python-sdk#55]
When triggering my http-py component which should return a random response, I keep getting the same response.

The following component should return a random The Office character, however when triggering the component either after `spin up`or [`spin deploy`](https://data-api-efrvs88z.fermyon.app/office-characters), I keep getting the same The Office character.

```python
from spin_http import Response
import json
import random


def handle_request(request):
    office_characters = {
        "Michael Scott": {
            "job_title": "Regional Manager",
            "age": 45,
            "hobbies": ["improv", "acting", "magic"],
            "salary": 75000,
            "actor": "Steve Carell",
        },
        "Dwight Schrute": {
            "job_title": "Assistant to the Regional Manager",
            "age": 35,
            "hobbies": ["farming", "beets", "bears"],
            "salary": 50000,
            "actor": "Rainn Wilson",
        },
        "Jim Halpert": {
            "job_title": "Salesman",
            "age": 30,
            "hobbies": ["pranks", "sports", "video games"],
            "salary": 50000,
            "actor": "John Krasinski",
        },
    #... many more characters' data here (Copilot generated)
    }

    random_office_character = random.choice(list(office_characters.keys()))

    utf8_encoded_office_character = json.dumps(
        office_characters[random_office_character]
    ).encode("utf-8")

    return Response(
        200,
        {"content-type": "application/json"},
        bytes(utf8_encoded_office_character),
    )
```

I rewrote as a Python script just as a sanity check for myself and the following Python script works as it should; returns a different The Office character every time it is run:

```python
import json
import random

def get_random_office_character():
    office_characters = {
        "Michael Scott": {
            "job_title": "Regional Manager",
            "age": 45,
            "hobbies": ["improv", "acting", "magic"],
            "salary": 75000,
            "actor": "Steve Carell",
        },
        #... many more characters' data here (Copilot generated)
    }

    random_office_character = random.choice(list(office_characters.keys()))
    character_info = office_characters[random_office_character]
    return character_info

def main():
    character_info = get_random_office_character()
    utf8_encoded_office_character = json.dumps(character_info, ensure_ascii=False).encode('utf-8')

    print(utf8_encoded_office_character.decode('utf-8'))

if __name__ == "__main__":
    main()

```

This is the Pipfile:
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]

[requires]
python_version = "3.10"
```

Below is the `spin.toml` file. The "pokemon" component is a http-py template.

```toml
spin_manifest_version = "1"
authors = ["kennethwolters <emailaddress>"]
description = "A Data API for trying out Fermyon"
name = "data-api"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "office-characters"
source = "office-characters/app.wasm"
[component.trigger]
route = "/office-characters"
[component.build]
command = "spin py2wasm app -o app.wasm"
workdir = "office-characters"
watch = ["app.py", "Pipfile"]

[[component]]
id = "pokemon"
source = "pokemon/app.wasm"
[component.trigger]
route = "/pokemon"
[component.build]
command = "spin py2wasm app -o app.wasm"
workdir = "pokemon"
watch = ["app.py", "Pipfile"]
```

In `.spin/logs/office-characters_stderr.txt` I can only find old logs (associated with a previous encoding error) and `.spin/logs/office-characters_stdout.txt` is empty.
